backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'projets'
    label: 'Projets'
    folder: 'content/projets'
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      # - {label: "URL", name: url, widget: string}
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Align Content", name: "align", widget: "select", options: ["vertical", "horizotal", "square"]}
      - { label: "Gallery", name: "galleryImages", widget: "list", summary: '{{fields.image}}', field: {label: Gallery Image, name: imgSrc, widget: image}}
      - { label: 'Publish Date', name: 'date', widget: 'datetime', default: "", format: 'Do MMM YY', date_format: "DD.MM.YYYY"}
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      

  - name: 'pages'
    label: 'Pages'
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        slug: '{{slug}}'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Textefr', name: 'texteFr', widget: 'markdown'}
          - {label: 'Texteen', name: 'texteEn', widget: 'markdown'}
          - {label: 'Legende1', name: 'legende1', widget: 'markdown'}
          - {label: 'Legende2', name: 'legende2', widget: 'markdown'}
          - {label: 'Legende3', name: 'legende3', widget: 'markdown'}
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.md"
        slug: '{{slug}}'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
              
  




